marysmartcollection/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

# project imports
from cart.views import (
    TransactionCreateView,
    TransactionDetailView,
    PaymentParamsView,
)
# app_name = "ecomflutterwave"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
    path('cart/update/<int:product_id>/', views.cart_update, name='cart_update'),
    path('cart/clear/', views.cart_clear, name='cart_clear'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path("transaction/", TransactionCreateView.as_view(), name="transaction_create"),
    path("payment-params/", PaymentParamsView.as_view(), name="payment_params"),
    path('checkout/square/', views.checkout_square, name='checkout_square'),
    # path("<str:tx_ref>/", TransactionDetailView.as_view(), name="transaction_detail"),
    

]

marysmartcollection/marysmartcollection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ecommerce.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('members/', include('django.contrib.auth.urls')),
    
    # Members URLs
    path('members/', include('members.urls', namespace='members')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marysmartcollection/members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('signup_user/', views.signup_user, name='signup_user'),
    path('forgotpass/', views.forgotpass, name='forgotpass'),
    path('profile/', views.profile, name='profile')
]

marysmartcollection/members/models.py
# Create your models here.
# models.py

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, Group, Permission
from django.utils.translation import gettext_lazy as _

class CustomUser(AbstractBaseUser, PermissionsMixin):
    full_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    number = models.CharField(max_length=15)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['email']

    groups = models.ManyToManyField(
        Group,
        verbose_name=_('groups'),
        blank=True,
        help_text=_(
            'The groups this user belongs to. A user will get all permissions '
            'granted to each of their groups.'
        ),
        related_name='customuser_groups',  # Add a unique related_name
    )

    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=_('user permissions'),
        blank=True,
        help_text=_('Specific permissions for this user.'),
        related_name='customuser_user_permissions',  # Add a unique related_name
    )

    def __str__(self):
        return self.email

marysmartcollection/members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.password_validation import validate_password
from Ecommerce.models import Category, Product 
from django.shortcuts import render, get_object_or_404
from .models import CustomUser

def login_user(request,category_slug=None):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    
    
    if request.method == 'POST':
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('kobosh:home')
        else:
            messages.error(request, "There was an error logging in. Please try again.")
            return redirect('members:login_user')

    context = {
        'category' : category,
        'categories': categories,
        'products': products
        }
    
   
    return render(request, 'members/login.html', context)


def signup_user(request,category_slug=None):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    
    if request.method == 'POST':
        full_name = request.POST.get("full_name")
        email = request.POST.get("email")
        password = request.POST.get("pass")
        password1 = request.POST.get("cpass")
        number = request.POST.get("number")

        # Check if passwords match
        if password != password1:
            messages.error(request, "Passwords do not match. Please try again.")
            return redirect('members:signup_user')

        # Validate password
        try:
            validate_password(password)
        except Exception as e:
            messages.error(request, str(e))
            return redirect('members:signup_user')

        # Check if email already exists
        if CustomUser.objects.filter(email=email).exists():
            messages.error(request, "Email already exists. Please use a different email.")
            return redirect('members:signup_user')

        # Create the user
        user = CustomUser.objects.create_user(email=email, password=password, number=number, full_name=full_name)
        user.save()

        return redirect('members:login_user')

    
    context = {
        'category' : category,
        'categories': categories,
        'products': products
        }


    return render(request, 'members/signup.html', context)

def forgotpass(request,category_slug=None):
    category = None
    categories = Category.objects.all()

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        products = products.filter(category=category)
    

    
    context = {
        'category' : category,
        'categories': categories,
        'products': products
        }
    return render(request, 'members/forgotpass.html', context)



def profile(request):
    context = {}
    
    if request.user.is_authenticated:
        user = request.user
        # full_name = user.full_name
        # number = user.number
        email = user.email

        context = {
            'email': email,
            # 'full_name': full_name,
            # 'number': number,
        }
    else:
        # Handle the case where the user is not authenticated (e.g., redirect to login page)
        return redirect('members:login_user') 
    return render(request, 'members/profilePage.html', context)

marysmartcollection/members/templates/members/forgotpass.html
{% extends 'kobosh/base.html' %}

{% load static %}
{% block 'content' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'kobosh/login&signup.css' %}">
    <style>
        .fa-user {
            color: #2be356;
        }
    </style>
</head>

<body>
    <div class="all_forms">
        <div class="reset create">
            <form action="" method="post">
                {% csrf_token %}
                <h2>Forgot Password</h2>
                <label for="input">
                    <strong>Reset email</strong>
                    <br>
                    <input id="full_name" type="email">
                </label><br><br>
                <input type="submit" value="Send reset mail" style="width: 96%;" class="account_create">
    
            </form>
        </div>
    </div>
</body>

</html>
{% endblock %}

marysmartcollection/members/templates/members/login.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mary Smart Collection - Fashion eCommerce HTML Template</title>
    <!-- favicon -->
    <link rel=icon href="{% static 'assets/img/favicon.png' %}" sizes="20x20" type="image/png">
    <!-- Vendor Stylesheet -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor.css' %}">
    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="{% static 'assets/css/login.css' %}">
    <!-- responsive Stylesheet -->
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

     
</head>

<body>
  <div class="container">
    <form class="login-form">
      <label for="upload" class="upload-label">
        <img src="{% static 'assets/img/logo-white.png' %}" alt="Upload Icon" id="uploadPreview" style="background-color: black; padding: 5px;" />

        <input type="file" id="upload" accept="image/*" onchange="previewImage(event)" />
      </label>

      <h2>Welcome to MarySmart Collections</h2>
      <p>Type your e-mail or phone number to log in or create an account.</p>

      <input type="email" placeholder="Email or Mobile Number*" required />

      <button type="submit" class="continue-btn">Continue</button>

      <small>By continuing you agree to MarySmart Collections’s <a href="#">Terms and Conditions</a></small>

      <button type="button" class="facebook-btn">Log in with Facebook</button>

      <p class="support-text">For further support, you may visit the Help Center or contact our customer service team.</p>

      <footer>MarySmart Collections</footer>
    </form>
  </div>

  <script>
    function previewImage(event) {
      const reader = new FileReader();
      reader.onload = function(){
        const output = document.getElementById('uploadPreview');
        output.src = reader.result;
      };
      reader.readAsDataURL(event.target.files[0]);
    }
  </script>
</body>
</html>

marysmartcollection/members/templates/members/profilePage.html
{% extends 'kobosh/base.html' %}
{% load static %}
{% block 'content' %}
{% load humanize %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .rightSide h4, .rightSide h2 {
            color: #2be356;
            margin: 10% 0% 0% 15%;

        }
        #accountHr {
            width: 75%;
            margin: 1% 0% 0% 15%;

        }
        .rightSide {
            background-color: white;
            height: 55pc;
            width: 55%;
            background-color: #dedede35;
            overflow: hidden;
            left: 10%;
            top: 9%;
            position: relative;
            margin: 5% 0% 0% 25%;
        }
        .containe {
            width: 100%;
            margin-top: -1%;
            height: 49pc;
            margin-bottom: 0;
        }
        .leftSide {
            position: absolute;
        }
        .btn {
            width: 16%;
            margin-top: 6%;
            height: 19%;
            cursor: pointer;
        }
        .bTn {
            width: 20%;
            /* height: 10%; */
            left: 20%;
            top: 9%;
            position: absolute;
        }
        .ali {
            /* width: 100%; */
            /* height: 6pc; */
            /* margin-top: 10%; */
            position: relative;
            top: 10.3pc;
            left: 22%;
            display: flex;
            flex-direction: column;
        }
                       
@media only screen and (max-width: 767px) {
    .rightSide h4, .rightSide h2 {
            color: #2be356;
            margin: 25% 0% 0% 8%;

        }
        .rightSide h2 {
            font-size: 15px;
            margin: 5% 0% 0% 8%;
        }
        .rightSide h4 {
            font-size: 9px;
        }
        #accountHr {
            width: 85%;
            margin: 1% 0% 0% 8%;

        }
        .rightSide {
            background-color: white;
            height: 34pc;
            width: 55%;
            background-color: #dedede35;
            overflow: hidden;
            left: 15%;
            top: 18%;
            position: relative;
            margin: 5% 0% 0% 25%;
        }
        .containe {
            width: 100%;
            margin-top: -1%;
            height: 25pc;
            margin-bottom: 0;
        }
        .leftSide {
            position: absolute;
        }
        .btn {
            width: 16%;
            margin-top: 6%;
            height: 19%;
            margin-left: 10px;
            cursor: pointer;
        }
        .bTn {
            width: 30%;
            /* height: 10%; */
            left: 5%;
            top: 31.5%;
            position: absolute;
        }
        .ali {
            /* width: 100%; */
            /* height: 6pc; */
            /* margin-top: 10%; */
            position: relative;
            top: 9.3pc;
            left: 10%;
            overflow: hidden;
            width: 85%;
            display: flex;
            flex-direction: column;
        }
}
    </style>
</head>
<body>
    <div class="containe">
        <div class="leftSide">
            <img class="bTn" src="{% static 'kobosh/accInfo.png' %}" alt="" />
           <div class="ali">
            <img class="btn" src="{% static 'kobosh/address.png' %}" alt="" />
            <img class="btn" onclick='location.href="{% url 'cart:cart_detail' %}"' | escapejs  src="{% static 'kobosh/cartt.png' %}" alt="" />
            <img class="btn" src="{% static 'kobosh/orders.png' %}" alt="" />
            <img class="btn" src="{% static 'kobosh/shop.png' %}" alt="" />
            <img class="btn" src="{% static 'kobosh/logout.png' %}" alt="" />
           </div>
        </div>
        <div class="rightSide">
            <h2>Account Information</h2>
            <hr id="accountHr" color="#2be356">
            <h4>FULL NAME: <span style="color: black;">{{ full_name }}</span></h4>
            <h4>EMAIL: <span style="color: black;">{{ email }} </h4>
            <h4>PHONE NUMBER: <span style="color: black;">{{ number }} </h4>
        </div>
    </div>
</body>
</html>
{% endblock %}

marysmartcollection/members/templates/members/signup.html
{% extends 'kobosh/base.html' %}
{% load static %}
{% block 'content' %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'kobosh/login&signup.css' %}">
    <style>
        .fa-user {
            color: #2be356;
        }
        @media screen and (max-width:767px) {
            input, label strong {
                position: relative;
                left: -15px;
            }
            input[type='submit']{
                position: relative;
                left: -12px;
            }
            .create h2, .create hr {
                width: 92%;
            }
        }
    </style>
</head>

<body>
   
    <div class="all_forms">
        <div class="create">
            <form action="" method="post" style="left: 8px; position: relative;">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
                {% csrf_token %}
                <h2>Create An Account</h2>
                <hr style="left: -9px; position: relative;" id="h2_id">
                <label for="input">
                    <strong>Full name</strong>
                    <br />
                    <input id="full_name" type="text" name="full_name" /> </label><br /><br />
                    <label for="input">
                        <strong>Phone Number</strong>
                        <br />
                        <input id="full_name" type="number" name="number" /> </label><br /><br />
                <label for="input">
                    <strong>Email</strong>
                    <br />
                    <input id="full_name" type="email" name="email" /> </label><br /><br />
                <label for="input">
                    <strong>Password</strong>
                    <br />
                    <input id="full_name" type="password" name="pass" /> </label><br /><br />
                <label for="input">
                    <strong>Confirm Password</strong>
                    <br />
                    <input id="full_name" type="password" name="cpass" /> </label><br />
                <br />
                <br />
    
                <input style="width: 95.4%;" type="submit" value="Create account" class="account_create" />
            </form>
            <div class="bottom">
                <p>By signing up you accept our <a href="#">terms and conditions</a> & <a href="#">privacy policy</a></p>
    
                <p>Already have an Account?</p>
                <input onclick="location.href='{% url 'members:login_user' %}'" style="left: 8px; position: relative;" id="create_acc" type="submit" value="Login">
    
                </div>
        </div>
    </div>
</body>

</html>
{% endblock %}